"""expand employee hr payroll workflows

Revision ID: 286a8ef79dcd
Revises: c62a9d31a290
Create Date: 2026-09-08 23:33:06.138977

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = '286a8ef79dcd'
down_revision = 'c62a9d31a290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_entity_type'), ['entity_type'], unique=False)

    op.create_table('compensation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_earnings', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wht', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('epf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('etf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paye', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compensation_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compensation_record_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_compensation_record_user_id'), ['user_id'], unique=False)

    op.create_table('leave_balance_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_balance_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['leave_balance_id'], ['leave_balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_balance_adjustment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balance_adjustment_leave_balance_id'), ['leave_balance_id'], unique=False)

    op.create_table('other_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('completed_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['completed_document_id'], ['employee_document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_request_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_other_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_other_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_other_request_user_id'), ['user_id'], unique=False)

    op.create_table('payslip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('compensation_record_id', sa.Integer(), nullable=True),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('payroll_month', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_earnings', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wht', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('epf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('etf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paye', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compensation_record_id'], ['compensation_record.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'payroll_year', 'payroll_month', 'version', name='uq_payslip_user_period_version')
    )
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslip_payroll_month'), ['payroll_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslip_payroll_year'), ['payroll_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslip_user_id'), ['user_id'], unique=False)

    op.create_table('public_holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date', 'location_id', 'entity_id', 'name', name='uq_public_holiday_scope')
    )
    with op.batch_alter_table('public_holiday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_holiday_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_holiday_holiday_date'), ['holiday_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_holiday_location_id'), ['location_id'], unique=False)

    op.create_table('other_request_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('other_request_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['other_request_id'], ['other_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_request_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_request_activity_other_request_id'), ['other_request_id'], unique=False)

    op.create_table('other_request_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('other_request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['other_request_id'], ['other_request.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_request_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_request_attachment_other_request_id'), ['other_request_id'], unique=False)

    with op.batch_alter_table('employee_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_employee_visible', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_employee_document_uploaded_by', 'user', ['uploaded_by_id'], ['id'])

    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('current_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('permanent_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('home_country_contact_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('personal_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_of_joining', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('probation_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('resignation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.String(length=30), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('employment_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('national_identity_card_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emirates_id_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emirates_id_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('passport_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('passport_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('account_holder_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('branch_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('swift_code', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('bank_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bank_currency', sa.String(length=3), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_profile_employment_status'), ['employment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_profile_resignation_date'), ['resignation_date'], unique=False)

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    with op.batch_alter_table('leave_balance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_year', sa.Integer(), nullable=False, server_default=str(date.today().year)))
        batch_op.add_column(sa.Column('entitled_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('accrued_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('utilized_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('carry_forward_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('adjustment_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.create_unique_constraint('uq_leave_balance_user_type_year', ['user_id', 'leave_type_id', 'calendar_year'])

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance_applied', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reviewer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_leave_request_cancellation_reviewer', 'user', ['cancellation_reviewer_id'], ['id'])
        batch_op.create_foreign_key('fk_leave_request_approver', 'user', ['approver_id'], ['id'])

    with op.batch_alter_table('leave_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('accrual_method', sa.String(length=30), nullable=False, server_default='annual'))
        batch_op.add_column(sa.Column('requires_manager_approval', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.create_unique_constraint('uq_leave_type_code', ['code'])

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='employee'))
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_column('role')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    with op.batch_alter_table('leave_type', schema=None) as batch_op:
        batch_op.drop_constraint('uq_leave_type_code', type_='unique')
        batch_op.drop_column('requires_manager_approval')
        batch_op.drop_column('accrual_method')
        batch_op.drop_column('code')

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leave_request_approver', type_='foreignkey')
        batch_op.drop_constraint('fk_leave_request_cancellation_reviewer', type_='foreignkey')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancellation_reviewer_id')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancellation_requested_at')
        batch_op.drop_column('balance_applied')
        batch_op.drop_column('approver_id')

    with op.batch_alter_table('leave_balance', schema=None) as batch_op:
        batch_op.drop_constraint('uq_leave_balance_user_type_year', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('adjustment_days')
        batch_op.drop_column('carry_forward_days')
        batch_op.drop_column('utilized_days')
        batch_op.drop_column('accrued_days')
        batch_op.drop_column('entitled_days')
        batch_op.drop_column('calendar_year')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('currency')
        batch_op.drop_column('country_code')
        batch_op.drop_column('legal_name')

    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_profile_resignation_date'))
        batch_op.drop_index(batch_op.f('ix_employee_profile_employment_status'))
        batch_op.drop_column('bank_currency')
        batch_op.drop_column('bank_address')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('swift_code')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('branch_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_holder_name')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_number')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('passport_expiry_date')
        batch_op.drop_column('passport_number')
        batch_op.drop_column('emirates_id_expiry_date')
        batch_op.drop_column('emirates_id_number')
        batch_op.drop_column('national_identity_card_number')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('nationality')
        batch_op.drop_column('gender')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('resignation_date')
        batch_op.drop_column('date_of_joining')
        batch_op.drop_column('probation_end_date')
        batch_op.drop_column('personal_email')
        batch_op.drop_column('home_country_contact_number')
        batch_op.drop_column('permanent_address')
        batch_op.drop_column('current_address')
        batch_op.drop_column('preferred_name')

    with op.batch_alter_table('employee_document', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_document_uploaded_by', type_='foreignkey')
        batch_op.drop_column('uploaded_by_id')
        batch_op.drop_column('is_employee_visible')
        batch_op.drop_column('file_size')
        batch_op.drop_column('mime_type')

    with op.batch_alter_table('other_request_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_other_request_attachment_other_request_id'))

    op.drop_table('other_request_attachment')
    with op.batch_alter_table('other_request_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_other_request_activity_other_request_id'))

    op.drop_table('other_request_activity')
    with op.batch_alter_table('public_holiday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_holiday_location_id'))
        batch_op.drop_index(batch_op.f('ix_public_holiday_holiday_date'))
        batch_op.drop_index(batch_op.f('ix_public_holiday_entity_id'))

    op.drop_table('public_holiday')
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslip_user_id'))
        batch_op.drop_index(batch_op.f('ix_payslip_payroll_year'))
        batch_op.drop_index(batch_op.f('ix_payslip_payroll_month'))

    op.drop_table('payslip')
    with op.batch_alter_table('other_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_other_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_other_request_status'))
        batch_op.drop_index(batch_op.f('ix_other_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_other_request_category'))

    op.drop_table('other_request')
    with op.batch_alter_table('leave_balance_adjustment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balance_adjustment_leave_balance_id'))

    op.drop_table('leave_balance_adjustment')
    with op.batch_alter_table('compensation_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compensation_record_user_id'))
        batch_op.drop_index(batch_op.f('ix_compensation_record_effective_date'))

    op.drop_table('compensation_record')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_event_actor_id'))

    op.drop_table('audit_event')
    # ### end Alembic commands ###
