"""add HR workflow models

Revision ID: 8e9ac58ce13b
Revises: 06e61c81490b
Create Date: 2026-09-07 19:54:19.463328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9ac58ce13b'
down_revision = '06e61c81490b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('default_days', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('birthday_voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voucher_code', sa.String(length=120), nullable=True),
    sa.Column('voucher_filename', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('available_days', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('designation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reporting_officer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_profile_reporting_officer', 'user', ['reporting_officer_id'], ['id'])
        batch_op.create_foreign_key('fk_profile_designation', 'designation', ['designation_id'], ['id'])
        batch_op.create_foreign_key('fk_profile_location', 'location', ['location_id'], ['id'])
        batch_op.create_foreign_key('fk_profile_department', 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_profile_entity', 'entity', ['entity_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_administrator', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('is_administrator')

    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profile_entity', type_='foreignkey')
        batch_op.drop_constraint('fk_profile_department', type_='foreignkey')
        batch_op.drop_constraint('fk_profile_location', type_='foreignkey')
        batch_op.drop_constraint('fk_profile_designation', type_='foreignkey')
        batch_op.drop_constraint('fk_profile_reporting_officer', type_='foreignkey')
        batch_op.drop_column('reporting_officer_id')
        batch_op.drop_column('designation_id')
        batch_op.drop_column('department_id')
        batch_op.drop_column('location_id')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')

    op.drop_table('password_reset_code')
    op.drop_table('notification')
    op.drop_table('leave_request')
    op.drop_table('leave_balance')
    op.drop_table('employee_document')
    op.drop_table('birthday_voucher')
    op.drop_table('leave_type')
    # ### end Alembic commands ###
