"""add generated HR document references

Revision ID: f1d40edf6835
Revises: 286a8ef79dcd
Create Date: 2026-09-09 00:15:23.103004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d40edf6835'
down_revision = '286a8ef79dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_reference', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('confirmation_stored_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confirmation_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confirmation_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_emailed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_generation_error', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_leave_request_confirmation_reference'), ['confirmation_reference'], unique=True)

    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_stored_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pdf_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pdf_generation_error', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_column('pdf_generation_error')
        batch_op.drop_column('pdf_generated_at')
        batch_op.drop_column('pdf_filename')
        batch_op.drop_column('pdf_stored_path')

    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_request_confirmation_reference'))
        batch_op.drop_column('confirmation_generation_error')
        batch_op.drop_column('confirmation_emailed_at')
        batch_op.drop_column('confirmation_generated_at')
        batch_op.drop_column('confirmation_filename')
        batch_op.drop_column('confirmation_stored_path')
        batch_op.drop_column('confirmation_reference')

    # ### end Alembic commands ###
